export const TYPED_ENV = {
  VITE_OPEN_WEATHER_API_BASE_URL: import.meta.env.VITE_OPEN_WEATHER_API_BASE_URL,
  VITE_OPEN_WEATHER_API_KEY: import.meta.env.VITE_OPEN_WEATHER_API_KEY,
  VITE_GOOGLE_CLIENT_ID: import.meta.env.VITE_GOOGLE_CLIENT_ID,
  VITE_AZURE_CLIENT_ID: import.meta.env.VITE_AZURE_CLIENT_ID
} as const;
